terraform {
  required_providers {
    aws = {
        source = "hashicorp/aws"
        version = "~> 6.0"
    }
  }
}

provider "aws" {
  region = "ap-south-1"
}

// you have to create main.tf file again to used these module and pass variables to module
// Also make sure to provide key-pair and pass through the public key path in aws_key_pair resource in resource.tf file
// create key pair by "ssh-keygen -t rsa" and while accessing the instance use .ppk file,
// and .ppk file can be generated by using puttygen tool,
// you have to load your private key generated by ssh-keygen
// and then save private key as .ppk file and use that .ppk file to access the instance through putty tool